apiVersion: v1
kind: Service

metadata:
  name: simple-go-service
  namespace: default
spec:
  selector:
    app: simple-go-server
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30090
  type: NodePort
